import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const SampleComponent = dynamic(
  // @ts-expect-error Federated module
  () => import("portal/components/BoringButton"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <SampleComponent />

        <Link href="/boring-page" className={styles.card}>
          <h2 className={inter.className}>
            Shared page <span>-&gt;</span>
          </h2>
          <p className={inter.className}>Switch to the shared remote page</p>
        </Link>
      </main>
    </>
  );
}
